install.packages("ggplot2")
install.packages("Hmisc")
install.packages("diveRsity", dependencies = TRUE)
install.packages("survival")
install.packages("survminer")
install.packages("FactoMineR")
install.packages("factoextra")
